added both steps
Jira ticket: CAMS-146

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -260,11 +260,9 @@ jobs:
     defaults:
       run:
         working-directory: user-interface
-
     runs-on: ubuntu-latest
     needs: [build-info]
     environment: ${{ needs.build-info.outputs.environment }}
-    continue-on-error: true
     steps:
       - uses: actions/checkout@v3
 
@@ -274,7 +272,12 @@ jobs:
           node-version: 18.17.1
           cache: "npm"
           cache-dependency-path: user-interface/package-lock.json
-
+      - name: fail build
+        id: build
+        run: exit 1
+      # - name: retry build
+      #   id: build2
+      #   run: echo "in retry"
       - name: Execute Build
         run: |
           pushd ../common
@@ -293,9 +296,6 @@ jobs:
       - name: Execute Coverage
         run: |
           CI=true npm run coverage
-      - name: fail build
-        id: build
-        run: exit 1
       - name: Package
         run: |
           mkdir artifacts
@@ -337,7 +337,7 @@ jobs:
   rerun-failed-build:
     runs-on: ubuntu-latest
     needs: [build-info, build-service, build-frontend]
-    if: always() && needs.build-frontend != 'success'
+    if: failure() && needs.build-frontend != 'success'
     steps:
       - uses: actions/checkout@v3
       - name: Rerun failed jobs in current workflow
@@ -453,6 +453,15 @@ jobs:
           in: ${{ needs.build-info.outputs.azResourceGrpAppEncrypted }}
 
       - name: Deploy to Azure WebApp
+        id: deploy-webapp-step
+        continue-on-error: true
+        run: |
+          ./ops/scripts/pipeline/az-app-deploy.sh \
+          --src ./${{ needs.build-info.outputs.webappName }}.tar \
+          -g ${{ steps.rgApp.outputs.out }} \
+          -n ${{ needs.build-info.outputs.webappName }}
+      - name: Deploy to Azure WebApp
+        if: steps.deploy-webapp-step.outcome != 'success'
         run: |
           ./ops/scripts/pipeline/az-app-deploy.sh \
           --src ./${{ needs.build-info.outputs.webappName }}.tar \
@@ -496,13 +505,13 @@ jobs:
           COSMOS_MANAGED_IDENTITY=${{ needs.deploy.outputs.cosmosDbClientId }}" \
           --identities "${{ needs.deploy.outputs.cosmosDbPrincipalId }}" \
           --identitiesResourceGroup ${{ secrets.AZURE_RG }}
-  rerun-failed-deploy:
-    runs-on: ubuntu-latest
-    needs: [build-info, deploy, deploy-webapp, deploy-service]
-    if: always() && needs.deploy-webapp.result != 'success' || always() && needs.deploy-service.result != 'success'
-    steps:
-      - name: Rerun failed jobs in current workflow
-        run: gh run rerun ${{github.run_id}} --failed
+  # rerun-failed-deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: [build-info, deploy, deploy-webapp, deploy-service]
+  #   if: always() && needs.deploy-webapp.result != 'success' || always() && needs.deploy-service.result != 'success'
+  #   steps:
+  #     - name: Rerun failed jobs in current workflow
+  #       run: gh run rerun ${{github.run_id}} --failed
   smoke-test-application:
     runs-on: ubuntu-latest
     needs: [build-info, deploy-webapp, deploy-service]
