added pwd for debugging
Jira ticket: CAMS-146

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -344,6 +344,8 @@ jobs:
     if: failure() && needs.build-frontend != 'success'
     steps:
       - uses: actions/checkout@v3
+      - name: get current dir
+        run: pwd
       - name: Rerun failed jobs in current workflow
         env:
           GH_TOKEN: ${{ github.token }}
@@ -496,6 +498,23 @@ jobs:
           in: ${{ needs.build-info.outputs.azResourceGrpAppEncrypted }}
 
       - name: Deploy Azure Functions backend
+        continue-on-error: true
+        id: deploy-backend-step
+        run: |
+          ./ops/scripts/pipeline/az-func-deploy.sh \
+          -g ${{ steps.rgApp.outputs.out }} \
+          -n ${{ needs.build-info.outputs.apiName }} \
+          --src ./${{ needs.build-info.outputs.apiName }}.zip \
+          --kvName ${{ secrets.AZ_KV_APP_CONFIG_NAME }} \
+          --kvSettings "MSSQL_HOST MSSQL_DATABASE_DXTR MSSQL_CLIENT_ID MSSQL_ENCRYPT MSSQL_TRUST_UNSIGNED_CERT FEATURE_FLAG_SDK_KEY" \
+          --settings "STARTING_MONTH=${{ vars.STARTING_MONTH }} \
+          COSMOS_ENDPOINT=https://${{ secrets.AZ_COSMOS_ACCOUNT_NAME }}.documents.azure.us:443/ \
+          COSMOS_DATABASE_NAME=${{ secrets.AZ_COSMOS_DATABASE_NAME }} \
+          COSMOS_MANAGED_IDENTITY=${{ needs.deploy.outputs.cosmosDbClientId }}" \
+          --identities "${{ needs.deploy.outputs.cosmosDbPrincipalId }}" \
+          --identitiesResourceGroup ${{ secrets.AZURE_RG }}
+      - name: Retry Deploy Azure Functions backend
+        if: steps.deploy-backend-step.outcome != 'success'
         run: |
           ./ops/scripts/pipeline/az-func-deploy.sh \
           -g ${{ steps.rgApp.outputs.out }} \
@@ -512,7 +531,7 @@ jobs:
   # rerun-failed-deploy:
   #   runs-on: ubuntu-latest
   #   needs: [build-info, deploy, deploy-webapp, deploy-service]
-  #   if: always() && needs.deploy-webapp.result != 'success' || always() && needs.deploy-service.result != 'success'
+  #   if: failure() && needs.deploy-webapp.result != 'success' || failure() && needs.deploy-service.result != 'success'
   #   steps:
   #     - name: Rerun failed jobs in current workflow
   #       run: gh run rerun ${{github.run_id}} --failed
