added slot handling logic in add ip script
Jira ticket: CAMS-160

Co-authored-by: Michael Ly <105381067+magile32@users.noreply.github.com>

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -556,9 +556,90 @@ jobs:
       #     --identitiesResourceGroup ${{ secrets.AZURE_RG }} \
       #     --slotName "staging"
 
-  smoke-test-application:
+  smoke-test-application-slots:
+    if: ((github.ref == 'refs/heads/main') || true)
     runs-on: ubuntu-latest
     needs: [build-info, deploy-webapp, deploy-service]
+    environment: ${{ needs.build-info.outputs.environment }}
+    env:
+      stackName: ${{ needs.build-info.outputs.stackName }}
+      webappName: ${{ needs.build-info.outputs.webappName }}
+      apiName: ${{ needs.build-info.outputs.apiName }}
+      slotName: ${{ needs.build-info.outputs.slotName }}
+      priority: 200
+    steps:
+      - uses: actions/checkout@v3
+      - uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          environment: ${{ vars.AZURE_ENVIRONMENT }}
+      - uses: cloudposse/github-action-secret-outputs@main
+        id: rgApp
+        with:
+          secret: ${{ secrets.PGP_SIGNING_PASSPHRASE }}
+          op: decode
+          in: ${{ needs.build-info.outputs.azResourceGrpAppEncrypted }}
+      - name: Enable GHA runner access
+        run: |
+          ops/scripts/pipeline/dev-add-allowed-ip.sh \
+          -g ${{ steps.rgApp.outputs.out }} \
+          -s ${{ env.stackName }} \
+          -p ${{ env.priority }} \
+          --slot-name ${{ env.priority }} \
+          --is-cicd
+      - name: Health check api
+        run: |
+          webStatusCode=$(curl -q -o -I -L -s -w "%{http_code}" --retry 5 --retry-delay 60 --retry-all-errors -f https://${{ env.webappName }}-${{ needs.build-info.outputs.slotName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }})
+          apiStatusCode=$(curl -q -o -I -L -s -w "%{http_code}" --retry 5 --retry-delay 60 --retry-all-errors -f https://${{ env.apiName }}-${{ needs.build-info.outputs.slotName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }}/api/healthcheck)
+
+          if [[ $webStatusCode = "200" && $apiStatusCode = "200" ]]; then
+            exit 0
+          else
+            echo "Health check error. Response codes webStatusCode=$webStatusCode apiStatusCode=$apiStatusCode"
+            exit 1
+          fi
+      - name: Execute Integration Tests
+        run: |
+          pushd backend/functions
+          npm ci
+          export CASES_FUNCTION_URL="https://${{ env.apiName }}-${{ needs.build-info.outputs.slotName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }}/api"
+          npm run test:integration
+          popd
+      - name: Disable GHA runner access
+        if: always()
+        run: |
+          name="gha-${{ env.priority }}-${{ env.stackName }}"
+          ops/scripts/pipeline/dev-rm-allowed-ip.sh ${{ steps.rgApp.outputs.out }} ${{ env.stackName }} ${name:0:32}
+  swap-webapp-deployment-slot:
+    runs-on: ubuntu-latest
+    needs:
+      [build-info, deploy-webapp, deploy-service, smoke-test-application-slots]
+    environment: ${{ needs.build-info.outputs.environment }}
+    env:
+      webappName: ${{ needs.build-info.outputs.webappName }}
+      slotName: ${{ needs.build-info.outputs.slotName }}
+    steps:
+      - name: Swap Deployment Slot
+        run: |
+          az webapp deployment slot swap --slot ${{ env.slotName }} --name ${{ env.webappName }} -g ${{ secrets.AZ_APP_RG }}
+
+  swap-nodeapi-deployment-slot:
+    runs-on: ubuntu-latest
+    needs:
+      [build-info, deploy-webapp, deploy-service, smoke-test-application-slots]
+    environment: ${{ needs.build-info.outputs.environment }}
+    env:
+      apiName: ${{ needs.build-info.outputs.apiName }}
+      slotName: ${{ needs.build-info.outputs.slotName }}
+    steps:
+      - name: Swap Deployment Slot
+        run: |
+          az webapp deployment slot swap --slot ${{ env.slotName }} --name ${{ env.apiName }} -g ${{ secrets.AZ_APP_RG }}
+
+  smoke-test-application:
+    runs-on: ubuntu-latest
+    needs:
+      [build-info, swap-nodeapi-deployment-slot, swap-webapp-deployment-slot]
     environment: ${{ needs.build-info.outputs.environment }}
     env:
       stackName: ${{ needs.build-info.outputs.stackName }}
@@ -585,27 +666,6 @@ jobs:
           -p ${{ env.priority }} \
           --is-cicd
       - name: Health check api
-        if: ((github.ref == 'refs/heads/main') || true)
-        run: |
-          webStatusCode=$(curl -q -o -I -L -s -w "%{http_code}" --retry 5 --retry-delay 60 --retry-all-errors -f https://${{ env.webappName }}-${{ needs.build-info.outputs.slotName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }})
-          apiStatusCode=$(curl -q -o -I -L -s -w "%{http_code}" --retry 5 --retry-delay 60 --retry-all-errors -f https://${{ env.apiName }}-${{ needs.build-info.outputs.slotName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }}/api/healthcheck)
-
-          if [[ $webStatusCode = "200" && $apiStatusCode = "200" ]]; then
-            exit 0
-          else
-            echo "Health check error. Response codes webStatusCode=$webStatusCode apiStatusCode=$apiStatusCode"
-            exit 1
-          fi
-      - name: Execute Integration Tests
-        if: ((github.ref == 'refs/heads/main') || true)
-        run: |
-          pushd backend/functions
-          npm ci
-          export CASES_FUNCTION_URL="https://${{ env.apiName }}-${{ needs.build-info.outputs.slotName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }}/api"
-          npm run test:integration
-          popd
-      - name: Health check api
-        if: ((github.ref != 'refs/heads/main') || false)
         run: |
           webStatusCode=$(curl -q -o -I -L -s -w "%{http_code}" --retry 5 --retry-delay 60 --retry-all-errors -f https://${{ env.webappName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }})
           apiStatusCode=$(curl -q -o -I -L -s -w "%{http_code}" --retry 5 --retry-delay 60 --retry-all-errors -f https://${{ env.apiName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }}/api/healthcheck)
@@ -617,19 +677,18 @@ jobs:
             exit 1
           fi
       - name: Execute Integration Tests
-        if: ((github.ref != 'refs/heads/main') || false)
         run: |
           pushd backend/functions
           npm ci
           export CASES_FUNCTION_URL="https://${{ env.apiName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }}/api"
           npm run test:integration
           popd
-      - name: Disable GHA runner access
-        if: always()
-        run: |
-          name="gha-${{ env.priority }}-${{ env.stackName }}"
-          ops/scripts/pipeline/dev-rm-allowed-ip.sh ${{ steps.rgApp.outputs.out }} ${{ env.stackName }} ${name:0:32}
 
+      # - name: Disable GHA runner access
+      #   if: always()
+      #   run: |
+      #     name="gha-${{ env.priority }}-${{ env.stackName }}"
+      #     ops/scripts/pipeline/dev-rm-allowed-ip.sh ${{ steps.rgApp.outputs.out }} ${{ env.stackName }} ${name:0:32}
   enable-access:
     runs-on: ubuntu-latest
     needs: [build-info, smoke-test-application]
