added post swap smoke tests
Jira ticket: CAMS-160

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -648,7 +648,7 @@ jobs:
           az webapp config access-restriction add --resource-group ${{ steps.rgApp.outputs.out }} --name ${{ env.webappName }} --rule-name AllowAll --action Allow --ip-address 0.0.0.0/0 --priority 100 1>/dev/null || true
           az functionapp config access-restriction add --resource-group ${{ steps.rgApp.outputs.out }} --name ${{ env.apiName }} --rule-name AllowAll --action Allow --ip-address 0.0.0.0/0 --priority 100 1>/dev/null || true
 
-##### Below are GHA jobs related to Azure Slot deployments #####
+  ##### Below are GHA jobs related to Azure Slot deployments #####
 
   deploy-webapp-slot:
     runs-on: ubuntu-latest
@@ -799,7 +799,12 @@ jobs:
   swap-webapp-deployment-slot:
     runs-on: ubuntu-latest
     needs:
-      [build-info, deploy-webapp-slot, deploy-service-slot, smoke-test-application-slots]
+      [
+        build-info,
+        deploy-webapp-slot,
+        deploy-service-slot,
+        smoke-test-application-slots,
+      ]
     environment: ${{ needs.build-info.outputs.environment }}
     env:
       webappName: ${{ needs.build-info.outputs.webappName }}
@@ -822,7 +827,12 @@ jobs:
   swap-nodeapi-deployment-slot:
     runs-on: ubuntu-latest
     needs:
-      [build-info, deploy-webapp-slot, deploy-service-slot, smoke-test-application-slots]
+      [
+        build-info,
+        deploy-webapp-slot,
+        deploy-service-slot,
+        smoke-test-application-slots,
+      ]
     environment: ${{ needs.build-info.outputs.environment }}
     env:
       apiName: ${{ needs.build-info.outputs.apiName }}
@@ -841,3 +851,57 @@ jobs:
       - name: Swap Deployment Slot
         run: |
           az webapp deployment slot swap --slot ${{ env.slotName }} --name ${{ env.apiName }} -g ${{ steps.rgApp.outputs.out }}
+  smoke-test-application-post-swap:
+    runs-on: ubuntu-latest
+    needs:
+      [build-info, swap-nodeapi-deployment-slot, swap-webapp-deployment-slot]
+    environment: ${{ needs.build-info.outputs.environment }}
+    env:
+      stackName: ${{ needs.build-info.outputs.stackName }}
+      webappName: ${{ needs.build-info.outputs.webappName }}
+      apiName: ${{ needs.build-info.outputs.apiName }}
+      priority: 200
+    steps:
+      - uses: actions/checkout@v3
+      - uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          environment: ${{ vars.AZURE_ENVIRONMENT }}
+      - uses: cloudposse/github-action-secret-outputs@main
+        id: rgApp
+        with:
+          secret: ${{ secrets.PGP_SIGNING_PASSPHRASE }}
+          op: decode
+          in: ${{ needs.build-info.outputs.azResourceGrpAppEncrypted }}
+      - name: Enable GHA runner access
+        run: |
+          ops/scripts/pipeline/dev-add-allowed-ip.sh \
+          -g ${{ steps.rgApp.outputs.out }} \
+          -s ${{ env.stackName }} \
+          -p ${{ env.priority }} \
+          --is-cicd
+      - name: Health check api
+        run: |
+          webStatusCode=$(curl -q -o -I -L -s -w "%{http_code}" --retry 5 --retry-delay 60 --retry-all-errors -f https://${{ env.webappName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }})
+          apiStatusCode=$(curl -q -o -I -L -s -w "%{http_code}" --retry 5 --retry-delay 60 --retry-all-errors -f https://${{ env.apiName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }}/api/healthcheck)
+
+          if [[ $webStatusCode = "200" && $apiStatusCode = "200" ]]; then
+            exit 0
+          else
+            echo "Health check error. Response codes webStatusCode=$webStatusCode apiStatusCode=$apiStatusCode"
+            exit 1
+          fi
+
+      - name: Execute Integration Tests
+        run: |
+          pushd backend/functions
+          npm ci
+          export CASES_FUNCTION_URL="https://${{ env.apiName }}.azurewebsites${{ vars.AZ_HOSTNAME_SUFFIX }}/api"
+          npm run test:integration
+          popd
+
+      - name: Disable GHA runner access
+        if: always()
+        run: |
+          name="gha-${{ env.priority }}-${{ env.stackName }}"
+          ops/scripts/pipeline/dev-rm-allowed-ip.sh ${{ steps.rgApp.outputs.out }} ${{ env.stackName }} ${name:0:32}
